-- Distill Seed Data: 50 content items
-- 10 per type: tip, signal, decoder, lens, framework
-- Distributed across roles and industries, all ≤80 words, ending with "So what?"

-- ─── TIPS (10) ───────────────────────────────────────────────────────────────

INSERT INTO content_items (type, body_text, role_tags, industry_tags, maturity_tags, worry_tags, generated_by) VALUES
('tip', 'Before your next AI vendor meeting, ask: "Show me a before-and-after metric from a real deployment." If they can''t, they''re selling potential, not performance. So what? As a senior leader, demanding proof of value—not proof of concept—is your most powerful AI filter.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY[]::TEXT[], ARRAY['evaluator'], ARRAY['vendor_evaluation'], 'curated'),

('tip', 'When evaluating AI projects, require a clear baseline metric before approving any budget. Without a starting point, you can''t measure ROI. So what? Insisting on measurable baselines turns AI experiments into business investments you can actually judge.', ARRAY['VP / SVP / EVP', 'BU Lead / Functional Head'], ARRAY[]::TEXT[], ARRAY['evaluator', 'pilot'], ARRAY['roi_clarity'], 'curated'),

('tip', 'Run a 30-day pilot before committing to any AI platform. Define success in writing before day 1. So what? A 30-day test costs less than a wrong 12-month contract and gives you the data to make the right call.', ARRAY['CU Lead / Practice Head', 'Product Sponsor / Owner'], ARRAY[]::TEXT[], ARRAY['evaluator', 'pilot'], ARRAY['roi_clarity', 'vendor_evaluation'], 'curated'),

('tip', 'Ask your team: "What manual process takes more than 2 hours per week?" That is your highest-probability AI use case. So what? CEOs who find their first AI win in operations—not strategy—build the credibility to fund bigger bets.', ARRAY['CEO / MD / President', 'BU Lead / Functional Head'], ARRAY[]::TEXT[], ARRAY['observer', 'evaluator'], ARRAY['roi_clarity'], 'curated'),

('tip', 'When a team presents an AI proposal, ask: "What happens if the AI is wrong?" A good answer reveals real thinking. A blank stare reveals a gap. So what? Risk planning separates AI theater from AI readiness in your organization.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY[]::TEXT[], ARRAY['pilot', 'scaler'], ARRAY['roi_clarity', 'vendor_evaluation'], 'curated'),

('tip', 'Add "AI implications" as a standing agenda item in your leadership team meetings. 15 minutes. Every other week. So what? Leaders who normalize AI conversations build the muscle memory to make faster decisions when real AI choices arrive.', ARRAY['CEO / MD / President'], ARRAY[]::TEXT[], ARRAY['observer', 'evaluator'], ARRAY['competitive_pressure', 'team_upskilling'], 'curated'),

('tip', 'Before any AI procurement, ask your legal team: "What data does this vendor process, where is it stored, and can I audit it?" So what? Most AI contracts have data clauses that executives never read—until there is a breach or a regulatory question.', ARRAY['VP / SVP / EVP', 'CU Lead / Practice Head'], ARRAY['Financial Services / Banking', 'Healthcare / Life Sciences'], ARRAY['evaluator'], ARRAY['vendor_evaluation'], 'curated'),

('tip', 'When an AI project misses its target, call a 30-minute postmortem and write down three things learned. Share it with one other team. So what? Organizations that learn from AI failures build better AI intuition than those who only celebrate AI wins.', ARRAY['BU Lead / Functional Head', 'CU Lead / Practice Head'], ARRAY[]::TEXT[], ARRAY['pilot', 'scaler'], ARRAY['roi_clarity', 'team_upskilling'], 'curated'),

('tip', 'Tell your team: "I want a 1-page memo on every AI tool you''re evaluating. Problem, solution, risk, cost." So what? Leaders who require structured thinking on AI avoid death-by-demo—where shiny tools get approved without business justification.', ARRAY['VP / SVP / EVP', 'Product Sponsor / Owner'], ARRAY['Technology / SaaS', 'Consulting / Professional Services'], ARRAY['evaluator', 'pilot'], ARRAY['vendor_evaluation', 'roi_clarity'], 'curated'),

('tip', 'Identify one AI-skeptic and one AI-enthusiast on your leadership team. Brief them together on every major AI decision. So what? Decisions made only with enthusiasts become expensive mistakes; decisions made only with skeptics become missed opportunities.', ARRAY['CEO / MD / President'], ARRAY[]::TEXT[], ARRAY['pilot', 'scaler'], ARRAY['team_upskilling', 'competitive_pressure'], 'curated');

-- ─── SIGNALS (10) ────────────────────────────────────────────────────────────

INSERT INTO content_items (type, body_text, role_tags, industry_tags, maturity_tags, worry_tags, generated_by) VALUES
('signal', 'JPMorgan now processes 200x more trade documents per analyst using AI. The result: faster compliance, lower error rates, and fewer junior analyst roles. So what? Every senior leader in financial services should ask which high-volume manual processes in their function are next.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY['Financial Services / Banking'], ARRAY['observer', 'evaluator'], ARRAY['competitive_pressure', 'roi_clarity'], 'curated'),

('signal', 'Microsoft reports Copilot users save an average of 3 hours per week on email and document work. That is 150 hours per year per person. So what? At scale, this is a budget and headcount conversation—not just a productivity one.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY['Technology / SaaS', 'Consulting / Professional Services'], ARRAY['observer', 'evaluator'], ARRAY['competitive_pressure', 'roi_clarity'], 'curated'),

('signal', 'A Stanford study found that AI-assisted customer service agents resolved issues 14% faster and reported higher job satisfaction. The pattern: AI handles repetition, humans handle judgment. So what? Your AI strategy should augment your best people, not replace your average ones.', ARRAY['BU Lead / Functional Head', 'CU Lead / Practice Head'], ARRAY['Retail / E-commerce', 'Technology / SaaS'], ARRAY['evaluator', 'pilot'], ARRAY['team_upskilling', 'roi_clarity'], 'curated'),

('signal', 'NHS hospitals using AI radiology tools are catching rare conditions 40% more accurately than solo physician review. Regulators are taking notice. So what? Healthcare leaders need an AI governance policy before regulators require one—being proactive beats being reactive.', ARRAY['CEO / MD / President', 'CU Lead / Practice Head'], ARRAY['Healthcare / Life Sciences'], ARRAY['observer', 'evaluator'], ARRAY['competitive_pressure', 'vendor_evaluation'], 'curated'),

('signal', 'Goldman Sachs and Morgan Stanley have both launched AI tools for financial advisors. Early data shows 25% faster client report generation. So what? Wealth and advisory firms that delay AI adoption risk losing talent to competitors who have already shipped it.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY['Financial Services / Banking'], ARRAY['observer', 'evaluator'], ARRAY['competitive_pressure'], 'curated'),

('signal', 'Amazon''s supply chain AI now predicts stockouts 3 weeks in advance with 89% accuracy—up from 71% using traditional forecasting. So what? Retail and logistics executives should benchmark their forecast accuracy now, because AI-driven competitors are rewriting customer expectations.', ARRAY['CEO / MD / President', 'BU Lead / Functional Head'], ARRAY['Retail / E-commerce', 'Manufacturing / Supply Chain'], ARRAY['observer', 'evaluator'], ARRAY['competitive_pressure', 'roi_clarity'], 'curated'),

('signal', 'McKinsey reports 70% of its consulting engagements now include an AI component. Junior consultant productivity has increased 35%. So what? If your consulting partners are using AI in your engagements, you should understand what it produces and how to review it.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY['Consulting / Professional Services'], ARRAY['observer', 'evaluator'], ARRAY['vendor_evaluation', 'competitive_pressure'], 'curated'),

('signal', 'Moderna used AI to design its COVID vaccine in just 2 days—a process that took years before. AI-accelerated R&D is now table stakes in biopharma. So what? Life sciences leaders who haven''t mapped AI to their R&D pipeline are already behind the competitive curve.', ARRAY['CEO / MD / President', 'CU Lead / Practice Head'], ARRAY['Healthcare / Life Sciences'], ARRAY['observer', 'evaluator'], ARRAY['competitive_pressure', 'roi_clarity'], 'curated'),

('signal', 'Salesforce reports that customers using Einstein AI close 30% more deals and forecast revenue 22% more accurately. The gap between AI-enabled and non-enabled sales teams is now measurable in revenue. So what? Every VP of Sales should pilot AI-assisted forecasting this quarter.', ARRAY['VP / SVP / EVP', 'BU Lead / Functional Head'], ARRAY['Technology / SaaS', 'Consulting / Professional Services'], ARRAY['evaluator', 'pilot'], ARRAY['roi_clarity', 'competitive_pressure'], 'curated'),

('signal', 'Google''s DeepMind AI reduced data center cooling energy by 30%. No new hardware—just better decisions made faster by AI. So what? Operational efficiency through AI is a boardroom story: cost savings, sustainability targets, and competitive differentiation in one investment.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY['Technology / SaaS', 'Manufacturing / Supply Chain'], ARRAY['evaluator', 'pilot'], ARRAY['roi_clarity', 'competitive_pressure'], 'curated');

-- ─── DECODERS (10) ───────────────────────────────────────────────────────────

INSERT INTO content_items (type, body_text, role_tags, industry_tags, maturity_tags, worry_tags, generated_by) VALUES
('decoder', 'What is a Foundation Model? Think of it as a powerful engine. Companies like Anthropic or OpenAI build it at enormous cost. You license access and build applications on top. So what? When a vendor pitches "our AI," ask which foundation model they use—it tells you half the capability story immediately.', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['observer', 'evaluator'], ARRAY['vendor_evaluation'], 'curated'),

('decoder', 'What is RAG (Retrieval Augmented Generation)? It means connecting an AI to your company''s own data, so it answers with your knowledge—not just general internet knowledge. So what? Any AI tool that works with your internal documents, policies, or client data is likely using RAG—which means your data quality directly impacts AI quality.', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['observer', 'evaluator'], ARRAY['vendor_evaluation', 'roi_clarity'], 'curated'),

('decoder', 'What is AI Hallucination? It means the AI confidently states something that is false. It doesn''t know it''s wrong—it just generates plausible-sounding text. So what? Every AI output that informs a business decision needs a human review layer—especially in regulated industries.', ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY['observer', 'evaluator'], ARRAY['vendor_evaluation', 'roi_clarity'], 'curated'),

('decoder', 'What is Fine-Tuning? It means taking a general AI model and training it further on your specific data to make it better at your specific tasks. So what? When a vendor says their model is "fine-tuned on financial data," ask: what data, how recent, and how do you validate its accuracy?', ARRAY['VP / SVP / EVP', 'CU Lead / Practice Head'], ARRAY[]::TEXT[], ARRAY['evaluator', 'pilot'], ARRAY['vendor_evaluation'], 'curated'),

('decoder', 'What is Agentic AI? It means AI that can take a sequence of actions autonomously—browsing the web, writing code, sending emails—without a human approving each step. So what? Before deploying agentic AI, your organization needs clear policies on what actions the AI is authorized to take.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY[]::TEXT[], ARRAY['evaluator', 'pilot', 'scaler'], ARRAY['vendor_evaluation', 'roi_clarity'], 'curated'),

('decoder', 'What is Token? In AI, a token is roughly ¾ of a word. When vendors charge "per token," a typical business email costs about 250–300 tokens to process. So what? When budgeting AI tools, ask for cost-per-token estimates on your actual use case—not list prices on hypothetical inputs.', ARRAY['VP / SVP / EVP', 'Product Sponsor / Owner'], ARRAY[]::TEXT[], ARRAY['evaluator', 'pilot'], ARRAY['roi_clarity', 'vendor_evaluation'], 'curated'),

('decoder', 'What is AI Governance? It means the policies, roles, and processes that decide how your organization builds, buys, and uses AI responsibly. So what? If your company doesn''t have an AI governance policy, you don''t have guardrails—which means the first AI mistake will be both expensive and avoidable.', ARRAY['CEO / MD / President', 'CU Lead / Practice Head'], ARRAY[]::TEXT[], ARRAY['observer', 'evaluator', 'pilot'], ARRAY['vendor_evaluation', 'roi_clarity'], 'curated'),

('decoder', 'What is a Vector Database? It is a special database that stores and retrieves AI-friendly data (embeddings) to enable fast, relevant search over large document libraries. So what? When vendors mention "semantic search" or "knowledge base AI," a vector database is the engine underneath—ask about their data retention policy.', ARRAY['VP / SVP / EVP', 'Product Sponsor / Owner'], ARRAY['Technology / SaaS'], ARRAY['evaluator', 'pilot'], ARRAY['vendor_evaluation'], 'curated'),

('decoder', 'What is Prompt Engineering? It is the practice of crafting input instructions (prompts) to get better AI outputs. A 10-word change to a prompt can double the quality of an AI response. So what? Your team''s ability to communicate clearly with AI tools is now a competitive skill—worth investing in training.', ARRAY['BU Lead / Functional Head', 'CU Lead / Practice Head'], ARRAY[]::TEXT[], ARRAY['pilot', 'scaler'], ARRAY['team_upskilling'], 'curated'),

('decoder', 'What is AI Bias? It means the AI systematically favors certain outputs based on patterns in its training data—often reflecting historical human biases. So what? Before deploying AI in hiring, lending, or customer decisions, require a bias audit—regulators in the US, EU, and UK are already watching.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY['Financial Services / Banking', 'Healthcare / Life Sciences'], ARRAY['evaluator', 'pilot'], ARRAY['vendor_evaluation', 'roi_clarity'], 'curated');

-- ─── LENS (10) ───────────────────────────────────────────────────────────────

INSERT INTO content_items (type, body_text, role_tags, industry_tags, maturity_tags, worry_tags, generated_by) VALUES
('lens', 'A Fortune 500 CFO faced a $2M AI audit tool pitch. Instead of approving it, she ran a 30-day pilot on one process. Result: 40% accuracy improvement, clear ROI. Pilot greenlit, full investment justified. So what? Pilots beat proposals—a 30-day test costs less than a wrong 2-year contract.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY['Financial Services / Banking', 'Consulting / Professional Services'], ARRAY['evaluator'], ARRAY['roi_clarity', 'vendor_evaluation'], 'curated'),

('lens', 'A retail CEO resisted AI personalization for 18 months, worried about customer privacy. When competitors gained 12% conversion lifts, she fast-tracked a privacy-first pilot. Lesson: waiting for perfect conditions is itself a risk. So what? Define your acceptable AI risk threshold now—before urgency forces a rushed decision.', ARRAY['CEO / MD / President'], ARRAY['Retail / E-commerce'], ARRAY['observer', 'evaluator'], ARRAY['competitive_pressure', 'roi_clarity'], 'curated'),

('lens', 'A VP of Operations discovered her team was using 11 different AI tools without IT knowledge. She ran an AI audit, standardized to 3 approved tools, saved $180K annually. So what? "AI sprawl" is the new shadow IT—and it''s your job to know what''s running in your function.', ARRAY['VP / SVP / EVP', 'BU Lead / Functional Head'], ARRAY[]::TEXT[], ARRAY['pilot', 'scaler'], ARRAY['roi_clarity', 'team_upskilling'], 'curated'),

('lens', 'A hospital CIO piloted AI radiology screening. After 3 months: 98% clinician adoption, 18% fewer missed diagnoses. His key: he had radiologists help design the workflow before launch. So what? AI adoption success is 30% technology and 70% change management—involve the people it affects from day one.', ARRAY['CU Lead / Practice Head', 'VP / SVP / EVP'], ARRAY['Healthcare / Life Sciences'], ARRAY['pilot', 'scaler'], ARRAY['team_upskilling', 'roi_clarity'], 'curated'),

('lens', 'A fintech CPO killed an AI feature that tested well internally but confused users in market research. The lesson: AI accuracy ≠ user value. She added an "explain why" feature—adoption tripled. So what? Measure what users do with AI output, not just whether the AI is technically correct.', ARRAY['Product Sponsor / Owner', 'VP / SVP / EVP'], ARRAY['Technology / SaaS', 'Financial Services / Banking'], ARRAY['pilot', 'scaler'], ARRAY['roi_clarity', 'vendor_evaluation'], 'curated'),

('lens', 'A supply chain VP used AI demand forecasting for one product line for 6 months, reduced overstock by 22%. When he tried to scale to all lines, it failed—different data quality. So what? AI scales well where data quality is consistent. Audit your data before you scale your AI.', ARRAY['BU Lead / Functional Head', 'VP / SVP / EVP'], ARRAY['Manufacturing / Supply Chain', 'Retail / E-commerce'], ARRAY['pilot', 'scaler'], ARRAY['roi_clarity', 'team_upskilling'], 'curated'),

('lens', 'A consulting firm managing partner added "AI implications" to every client engagement. Billable hours from AI-related work grew 40% in 12 months. His team learned by doing. So what? Leaders who create structured opportunities for their teams to practice AI build capability faster than any training program.', ARRAY['CU Lead / Practice Head', 'CEO / MD / President'], ARRAY['Consulting / Professional Services'], ARRAY['evaluator', 'pilot'], ARRAY['team_upskilling', 'competitive_pressure'], 'curated'),

('lens', 'A pharma VP approved an AI drug interaction tool after one vendor demo. 6 months later, it failed a regulatory review—the training data was 4 years old. So what? Always ask your AI vendor: "How current is the training data, and how often is it updated?" This is not a technical question—it''s a risk question.', ARRAY['VP / SVP / EVP', 'CU Lead / Practice Head'], ARRAY['Healthcare / Life Sciences'], ARRAY['evaluator'], ARRAY['vendor_evaluation', 'roi_clarity'], 'curated'),

('lens', 'A SaaS CEO made AI literacy a performance goal for his entire leadership team—not just tech leaders. Year 1: internal AI project approvals went from 3 to 14. Year 2: revenue from AI-enhanced products doubled. So what? AI literacy is a leadership multiplier—not just a skill for engineers.', ARRAY['CEO / MD / President'], ARRAY['Technology / SaaS'], ARRAY['pilot', 'scaler'], ARRAY['team_upskilling', 'competitive_pressure'], 'curated'),

('lens', 'A banking BU Lead asked his team to document every process that took >1 hour per week. 3 months later, AI automated 4 of them, saving 1,200 staff hours monthly. His insight: the bottleneck wasn''t the AI—it was identifying the right problems. So what? Problem clarity is the scarcest resource in AI projects, not computing power.', ARRAY['BU Lead / Functional Head', 'VP / SVP / EVP'], ARRAY['Financial Services / Banking'], ARRAY['evaluator', 'pilot'], ARRAY['roi_clarity', 'team_upskilling'], 'curated');

-- ─── FRAMEWORKS (10) ─────────────────────────────────────────────────────────

INSERT INTO content_items (type, body_text, role_tags, industry_tags, maturity_tags, worry_tags, generated_by) VALUES
('framework', '5 questions for any AI vendor: 1) What specific problem does this solve? 2) Show me a real client result with numbers. 3) What data does it need? 4) How do you handle errors? 5) What is the exit cost? So what? Vendors who struggle with these questions are selling a story, not a solution.', ARRAY['VP / SVP / EVP', 'Product Sponsor / Owner'], ARRAY[]::TEXT[], ARRAY['evaluator'], ARRAY['vendor_evaluation'], 'curated'),

('framework', 'The 3-Gate AI Budget Check: Gate 1 — Is the problem real and recurring? Gate 2 — Is there a measurable success metric? Gate 3 — Is there a human fallback if AI fails? All three gates must pass before approving AI investment. So what? This filter alone prevents 70% of bad AI spend decisions.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY[]::TEXT[], ARRAY['observer', 'evaluator'], ARRAY['roi_clarity', 'vendor_evaluation'], 'curated'),

('framework', 'The AI ROI Formula: (Time saved × hourly cost) + (Error reduction × cost per error) + (Revenue gain from better decisions) - (Tool cost + implementation cost). Run this before approving any AI project. So what? Most AI investments look obvious when quantified and ridiculous when not.', ARRAY['CEO / MD / President', 'BU Lead / Functional Head'], ARRAY[]::TEXT[], ARRAY['evaluator', 'pilot'], ARRAY['roi_clarity'], 'curated'),

('framework', 'AI Readiness Assessment (5 minutes): 1) Do we have clean, accessible data for this use case? 2) Do we have someone who can evaluate AI quality? 3) Is there executive sponsorship? 4) Is there a defined pilot timeline? If 3 or more are "no," the project will likely fail regardless of the AI quality. So what? Organizational readiness predicts AI success more than technology choice.', ARRAY['CU Lead / Practice Head', 'VP / SVP / EVP'], ARRAY[]::TEXT[], ARRAY['observer', 'evaluator'], ARRAY['roi_clarity', 'team_upskilling'], 'curated'),

('framework', 'The AI Governance Minimum: 1) A list of approved AI tools by function. 2) A data classification policy (what data can AI touch?). 3) An escalation process for AI errors. 4) A review cadence (quarterly). That is it. Start small. So what? Companies that wait for a perfect policy end up with no policy—and their first AI incident sets the policy instead.', ARRAY['CEO / MD / President', 'CU Lead / Practice Head'], ARRAY[]::TEXT[], ARRAY['pilot', 'scaler'], ARRAY['vendor_evaluation', 'roi_clarity'], 'curated'),

('framework', 'Evaluating AI vendors: 4-factor scoring. Score 1-5 on each: Data privacy practices, Accuracy on your specific use case (not their benchmarks), Implementation support quality, Total cost of ownership over 2 years. Anyone scoring below 12 total = decline. So what? This framework keeps vendor selection rational when everyone in the room is excited.', ARRAY['VP / SVP / EVP', 'Product Sponsor / Owner'], ARRAY[]::TEXT[], ARRAY['evaluator'], ARRAY['vendor_evaluation'], 'curated'),

('framework', 'The AI Meeting Prep Protocol: 1) 30 min before: Google "[vendor] AI case study [your industry]". 2) During demo: ask "what does it do when it''s wrong?" 3) After demo: ask yourself "can I explain what I just saw in 2 sentences?" If not, ask more questions. So what? This simple protocol transforms you from a passive observer into an informed decision-maker.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY[]::TEXT[], ARRAY['observer', 'evaluator'], ARRAY['vendor_evaluation', 'roi_clarity'], 'curated'),

('framework', 'AI Use Case Prioritization Matrix: Score each potential AI project on: 1) Business impact (1–5), 2) Data readiness (1–5), 3) Implementation speed (1–5), 4) Risk level (5=low risk, 1=high). Total score determines sequencing. So what? This prevents the classic mistake of pursuing the sexiest AI project instead of the fastest-to-value one.', ARRAY['BU Lead / Functional Head', 'CU Lead / Practice Head'], ARRAY[]::TEXT[], ARRAY['evaluator', 'pilot'], ARRAY['roi_clarity', 'competitive_pressure'], 'curated'),

('framework', 'The Team AI Readiness Audit: Ask each of your direct reports: "Name one task in your role that could be automated by AI, and one decision where AI could improve your accuracy." Their answers reveal AI literacy gaps you need to close. So what? Knowing where your team is—not where you hope they are—is the foundation of any credible AI upskilling plan.', ARRAY['CEO / MD / President', 'VP / SVP / EVP'], ARRAY[]::TEXT[], ARRAY['observer', 'evaluator'], ARRAY['team_upskilling'], 'curated'),

('framework', 'The AI Pilot Design Template: Define before day 1 — Problem statement (1 sentence), Success metric (1 number), Timeline (30/60/90 days), Owner (1 person), Failure criteria (what would make you stop?). So what? AI pilots without failure criteria don''t fail—they just drift. Pre-defining the exit condition forces everyone to stay honest about results.', ARRAY['VP / SVP / EVP', 'Product Sponsor / Owner', 'CU Lead / Practice Head'], ARRAY[]::TEXT[], ARRAY['pilot'], ARRAY['roi_clarity', 'vendor_evaluation'], 'curated');
