import type { TestHarnessPayload } from './payload-types'

/**
 * B2B-32 (docs/specs/B2B-32-requirement-document.md §0 point 10b, §6.9, AT-15, AT-16).
 *
 * Pure payload-to-collection builder, deliberately separated from the DOM-triggering download
 * logic (which lives in the Screen C client component, since `Blob`/`URL.createObjectURL` need a
 * browser) so this function is unit-testable and so the exact same object built here is what the
 * client component both renders on screen and serializes to a file — no drift (AT-16).
 *
 * The real `TEST_HARNESS_PARTNER_API_KEY` is NEVER passed into this function or embedded in its
 * output (AT-15) — the `Authorization` header is the literal template string
 * `"Bearer {{TEST_HARNESS_API_KEY}}"`, a Postman collection variable left blank, which Arun fills
 * in himself once in his own Postman environment.
 */

export interface PostmanCollectionV21 {
  info: { name: string; description: string; schema: string }
  item: Array<{
    name: string
    request: {
      method: string
      header: Array<{ key: string; value: string }>
      url: { raw: string; protocol: string; host: string[]; path: string[] }
      body: { mode: string; raw: string }
    }
  }>
  variable: Array<{ key: string; value: string; type: string }>
}

export function buildPostmanCollection(topicTitle: string, payload: TestHarnessPayload): PostmanCollectionV21 {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://distill-peach.vercel.app'
  const sessionsUrl = `${appUrl}/api/partner/v1/sessions`

  return {
    info: {
      name: `Clio Test Harness — ${topicTitle || 'Untitled topic'}`,
      description:
        'Generated by test.hello-clio.com. Set the TEST_HARNESS_API_KEY collection variable to the ' +
        "harness's real partner API key before sending — the key is never embedded in this file.",
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    item: [
      {
        name: 'Dispatch test session',
        request: {
          method: 'POST',
          header: [
            { key: 'Authorization', value: 'Bearer {{TEST_HARNESS_API_KEY}}' },
            { key: 'Content-Type', value: 'application/json' },
          ],
          url: {
            raw: sessionsUrl,
            protocol: 'https',
            host: new URL(appUrl).hostname.split('.'),
            path: ['api', 'partner', 'v1', 'sessions'],
          },
          body: { mode: 'raw', raw: JSON.stringify(payload, null, 2) },
        },
      },
    ],
    variable: [{ key: 'TEST_HARNESS_API_KEY', value: '', type: 'string' }],
  }
}

/** Filesystem-safe slug for the downloaded collection's filename. */
export function slugify(text: string): string {
  return (
    text
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'untitled'
  )
}
