'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useRouter } from 'next/navigation'
import { CheckCircle, ArrowRight, Sparkles, BookOpen, LayoutList, Lock } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { TopicTree } from '@/components/plan/TopicTree'
import { PlanSkeleton } from '@/components/plan/PlanSkeleton'
import { ArcSection } from '@/components/plan/ArcSection'
import { RecommendationCard, type RecommendationData } from '@/components/plan/RecommendationCard'
import { buildCurriculumFromSelection } from '@/lib/content/curriculum-from-selection'
import { buildCurriculum, type CurriculumPlan } from '@/lib/content/curriculum'

interface User {
  id: string
  email: string | null
  plan_tier: string | null
  ai_maturity: string | null
  topic_interests: string[] | null
  curriculum_plan: unknown
  plan_approved: boolean | null
  minutes_balance: number | null
  minutes_included: number | null
}

interface CurriculumSession {
  session_id: string
  title: string
  focus: string
  arc_position: number
  arc_length: number
  depth_level: 'beginner' | 'intermediate' | 'advanced'
  estimated_minutes: number
  arc_name: string
  arc_type: 'domain' | 'integrated' | 'singleton'
  is_visible?: boolean
  queue_rationale?: string | null
}

type ViewState = 'loading' | 'generating' | 'approval' | 'active' | 'fallback'
type Tab = 'ai-plan' | 'browse'

const RECOMMENDATION_LIMIT: Record<string, number> = {
  executive: 2,
  pro: 2,
  starter: 1,
}

export default function PlanClient({ user }: { user: User }) {
  const router = useRouter()
  const [tab, setTab] = useState<Tab>('ai-plan')
  const [viewState, setViewState] = useState<ViewState>('loading')

  // Intelligent curriculum state
  const [planId, setPlanId] = useState<string | null>(null)
  const [visibleSessions, setVisibleSessions] = useState<CurriculumSession[]>([])
  const [completedIds, setCompletedIds] = useState<Set<string>>(new Set())
  const [recommendations, setRecommendations] = useState<RecommendationData[]>([])
  const [isPlanApproved, setIsPlanApproved] = useState(user.plan_approved ?? false)
  const [approving, setApproving] = useState(false)
  const [approvingMessage, setApprovingMessage] = useState('')
  const [isFallback, setIsFallback] = useState(false)
  const pollingRef = useRef<ReturnType<typeof setInterval> | null>(null)

  // Browse tab state
  const [customPlan, setCustomPlan] = useState<CurriculumPlan | null>(null)
  const [building, setBuilding] = useState(false)

  const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [
    { id: 'ai-plan', label: 'AI Plan', icon: <Sparkles size={14} /> },
    { id: 'browse', label: 'Browse Catalog', icon: <BookOpen size={14} /> },
  ]

  const recLimit = RECOMMENDATION_LIMIT[user.plan_tier ?? 'free'] ?? 0

  // ─── Fetch current plan ───────────────────────────────────────────────────

  const fetchPlan = useCallback(async () => {
    const res = await fetch('/api/curriculum/plan?check_generating=true')
    if (!res.ok) return null
    return res.json() as Promise<{
      plan: { id: string; visible_sessions: CurriculumSession[]; is_approved: boolean; generated_at: string } | null
      completions: string[]
      recommendations: RecommendationData[]
      is_generating: boolean
    }>
  }, [])

  // ─── Bootstrap: ensure topics saved, then generate or load plan ──────────

  useEffect(() => {
    async function bootstrap() {
      let topics = user.topic_interests ?? []

      if (topics.length === 0) {
        try {
          const raw = localStorage.getItem('clio_onboarding')
          if (raw) {
            const onboarding = JSON.parse(raw) as Record<string, unknown>
            const localTopics = Array.isArray(onboarding.selectedTopics)
              ? (onboarding.selectedTopics as string[]).filter((t) => typeof t === 'string' && t.length > 0)
              : []
            if (localTopics.length > 0) {
              await fetch('/api/topics', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ topics: localTopics }),
              })
              topics = localTopics
            }
          }
        } catch { /* ignore */ }
      }

      if (topics.length === 0) {
        // No topics at all — redirect to topic selection
        router.push('/topics')
        return
      }

      // Check if we already have a plan (generated by Inngest in the background)
      const existing = await fetchPlan()
      const existingPlan = existing?.plan
      const hasSessions = existingPlan && Array.isArray(existingPlan.visible_sessions) && existingPlan.visible_sessions.length > 0
      const isCachedFallback = hasSessions && (existingPlan as { is_fallback?: boolean }).is_fallback === true
      if (hasSessions && !isCachedFallback) {
        setPlanId(existingPlan.id)
        setVisibleSessions(existingPlan.visible_sessions)
        setCompletedIds(new Set(existing.completions))
        setRecommendations((existing.recommendations ?? []).slice(0, recLimit))
        setIsPlanApproved(existingPlan.is_approved)
        setViewState(existingPlan.is_approved ? 'active' : 'approval')
        return
      }
      // Cached fallback detected — supersede it and generate a real plan
      if (isCachedFallback) {
        await fetch('/api/curriculum/generate', { method: 'POST' })
      }

      // Plan not ready yet — Inngest job is still running.
      // Poll every 4 seconds until the plan appears.
      setViewState('generating')

      let elapsed = 0
      const POLL_INTERVAL = 4000
      const FALLBACK_TIMEOUT = 90000  // after 90s, call generate directly as safety net

      const planPoll = setInterval(async () => {
        elapsed += POLL_INTERVAL

        const polled = await fetchPlan()
        if (polled?.plan && Array.isArray(polled.plan.visible_sessions) && polled.plan.visible_sessions.length > 0) {
          clearInterval(planPoll)
          setPlanId(polled.plan.id)
          setVisibleSessions(polled.plan.visible_sessions)
          setCompletedIds(new Set(polled.completions))
          setRecommendations((polled.recommendations ?? []).slice(0, recLimit))
          setIsPlanApproved(polled.plan.is_approved)
          setViewState(polled.plan.is_approved ? 'active' : 'approval')
          return
        }

        // Safety fallback: if Inngest failed all retries, generate directly from browser
        if (elapsed >= FALLBACK_TIMEOUT) {
          clearInterval(planPoll)
          const genRes = await fetch('/api/curriculum/generate', { method: 'POST' })
          if (!genRes.ok) {
            const maturity = user.ai_maturity ?? 'intermediate'
            const simplePlan = buildCurriculum(topics, maturity)
            const fakeSessions: CurriculumSession[] = simplePlan.sessions.flatMap((s, si) =>
              s.topics.map((l, li) => ({
                session_id: `fallback-${si}-${li}`,
                title: l.title,
                focus: l.subtopics?.[0] ?? l.title,
                arc_position: li + 1,
                arc_length: s.topics.length,
                depth_level: l.difficulty,
                estimated_minutes: ([15, 20, 25, 30].includes(l.estimatedMinutes) ? l.estimatedMinutes : 20) as 15 | 20 | 25 | 30,
                arc_name: 'Your Learning Path',
                arc_type: 'singleton' as const,
              }))
            )
            setVisibleSessions(fakeSessions)
            setIsFallback(true)
            setViewState('fallback')
            return
          }
          const genData = await genRes.json() as {
            plan_id: string; visible_sessions: CurriculumSession[]; is_approved: boolean; is_fallback?: boolean
          }
          setPlanId(genData.plan_id)
          setVisibleSessions(genData.visible_sessions ?? [])
          setIsFallback(genData.is_fallback ?? false)
          setIsPlanApproved(genData.is_approved)
          setViewState(genData.is_approved ? 'active' : 'approval')
        }
      }, POLL_INTERVAL)
    }

    bootstrap()
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // ─── Polling for recommendation generation completion ─────────────────────

  function startPolling() {
    if (pollingRef.current) return
    pollingRef.current = setInterval(async () => {
      const data = await fetchPlan()
      if (!data) return
      setVisibleSessions(data.plan?.visible_sessions ?? [])
      setCompletedIds(new Set(data.completions))
      setRecommendations((data.recommendations ?? []).slice(0, recLimit))
      if (!data.is_generating && pollingRef.current) {
        clearInterval(pollingRef.current)
        pollingRef.current = null
      }
    }, 5000)
  }

  useEffect(() => {
    return () => { if (pollingRef.current) clearInterval(pollingRef.current) }
  }, [])

  // ─── Regenerate plan (for fallback plans when API key becomes available) ──

  async function handleRegenerate() {
    setViewState('generating')
    setPlanId(null)
    setVisibleSessions([])
    try {
      const genRes = await fetch('/api/curriculum/generate', { method: 'POST' })
      if (!genRes.ok) throw new Error('Generate failed')
      const genData = await genRes.json() as {
        plan_id: string
        visible_sessions: CurriculumSession[]
        is_approved: boolean
        is_fallback?: boolean
      }
      setPlanId(genData.plan_id)
      setVisibleSessions(genData.visible_sessions ?? [])
      setIsFallback(genData.is_fallback ?? false)
      setIsPlanApproved(genData.is_approved)
      setViewState(genData.is_approved ? 'active' : 'approval')
    } catch {
      setViewState('fallback')
    }
  }

  // ─── Approve plan ─────────────────────────────────────────────────────────

  async function handleApprove() {
    setApproving(true)
    setApprovingMessage('Approving your plan…')

    const MAX_WAIT_MS = 60_000
    const RETRY_INTERVAL_MS = 3_000
    const started = Date.now()

    const tryApprove = async (): Promise<void> => {
      const res = await fetch('/api/plan/approve', { method: 'POST' })

      if (res.ok) {
        // Sessions are ready — reload plan and navigate to schedule setup
        const refreshed = await fetchPlan()
        if (refreshed?.plan?.visible_sessions) {
          setVisibleSessions(refreshed.plan.visible_sessions)
        }
        setIsPlanApproved(true)
        setViewState('active')
        setApproving(false)
        setApprovingMessage('')
        router.push('/dashboard/schedule-setup')
        return
      }

      const data = await res.json().catch(() => ({})) as { code?: string }

      // Sessions not designed yet — Inngest still running, retry after a short wait
      if (res.status === 409 && data.code === 'SESSIONS_NOT_READY') {
        if (Date.now() - started < MAX_WAIT_MS) {
          setApprovingMessage('Preparing your sessions… almost ready')
          await new Promise((r) => setTimeout(r, RETRY_INTERVAL_MS))
          return tryApprove()
        }
        // Timed out waiting for Inngest — unblock the user
        setApproving(false)
        setApprovingMessage('')
        alert('Session preparation is taking longer than expected. Please wait a moment and try again.')
        return
      }

      setApproving(false)
      setApprovingMessage('')
      alert('Something went wrong. Please try again.')
    }

    try {
      await tryApprove()
    } catch {
      setApproving(false)
      setApprovingMessage('')
      alert('Something went wrong. Please try again.')
    }
  }

  // ─── Session complete ─────────────────────────────────────────────────────

  async function handleSessionComplete(sessionId: string, method: 'explicit' | 'time_threshold' = 'explicit') {
    const res = await fetch('/api/curriculum/complete-session', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ session_id: sessionId, time_spent_seconds: 0, method }),
    })
    if (res.ok) {
      const data = await res.json() as { promoted_sessions: unknown[] }
      setCompletedIds((prev) => new Set([...Array.from(prev), sessionId]))
      if (data.promoted_sessions?.length > 0) {
        const refreshed = await fetchPlan()
        if (refreshed?.plan) setVisibleSessions(refreshed.plan.visible_sessions)
      }
    }
  }

  // ─── Recommendation actions ───────────────────────────────────────────────

  async function handleAcceptRecommendation(sessionId: string) {
    const res = await fetch('/api/curriculum/accept-recommendation', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ session_id: sessionId }),
    })
    if (res.ok) {
      setRecommendations((prev) => prev.filter((r) => r.session_id !== sessionId))
      startPolling()
    }
  }

  async function handleDismissRecommendation(sessionId: string) {
    await fetch('/api/curriculum/dismiss-recommendation', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ session_id: sessionId }),
    })
    setRecommendations((prev) => prev.filter((r) => r.session_id !== sessionId))
  }

  // ─── Browse tab ───────────────────────────────────────────────────────────

  function handleBuildFromSelection(selectedLessonIds: string[]) {
    setBuilding(true)
    try {
      const built = buildCurriculumFromSelection(selectedLessonIds)
      setCustomPlan(built)
    } finally {
      setBuilding(false)
    }
  }

  // ─── Group sessions by arc ────────────────────────────────────────────────

  const arcGroups = visibleSessions.reduce<Map<string, { sessions: CurriculumSession[]; arcType: 'domain' | 'integrated' | 'singleton' }>>(
    (map, s) => {
      const key = s.arc_name ?? 'Your Learning Path'
      if (!map.has(key)) map.set(key, { sessions: [], arcType: s.arc_type ?? 'singleton' })
      map.get(key)!.sessions.push(s)
      return map
    },
    new Map()
  )

  const completedCount = visibleSessions.filter((s) => completedIds.has(s.session_id)).length
  const totalVisible = visibleSessions.length
  const totalMins = visibleSessions.reduce((sum, s) => sum + s.estimated_minutes, 0)

  const firstIncomplete = visibleSessions.find((s) => !completedIds.has(s.session_id))

  const isFreeOrTrial = !user.plan_tier || user.plan_tier === 'free' || user.plan_tier === 'trial'

  // ─── States ───────────────────────────────────────────────────────────────

  if (viewState === 'loading' || viewState === 'generating') {
    return (
      <PlanSkeleton
        message={
          viewState === 'generating'
            ? 'Analysing your topic selection and role to create an intelligent learning path.'
            : 'Loading your plan…'
        }
      />
    )
  }

  return (
    <div className="space-y-8 max-w-4xl">
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Sparkles size={18} className="text-[#7C3AED]" />
              <span className="text-xs font-semibold text-[#7C3AED] uppercase tracking-wider">
                Your Learning Plan
              </span>
            </div>
            {isPlanApproved ? (
              <>
                <h1 className="text-3xl font-bold text-white mb-1">Your learning plan</h1>
                <p className="text-[#94A3B8]">
                  {completedCount} of {totalVisible} sessions complete
                </p>
              </>
            ) : (
              <>
                <h1 className="text-3xl font-bold text-white mb-1">Your personalised learning plan</h1>
                <p className="text-[#94A3B8]">
                  {isFallback
                    ? "We're still building your full personalised plan — it'll be ready shortly."
                    : 'Based on your topics and role. Review and approve to begin.'}
                </p>
                {isFallback && !isPlanApproved && (
                  <button
                    onClick={handleRegenerate}
                    className="mt-2 text-sm text-[#7C3AED] hover:text-[#A855F7] transition-colors underline underline-offset-2"
                  >
                    Try generating the full plan →
                  </button>
                )}
              </>
            )}
          </div>

          {tab === 'ai-plan' && (
            isPlanApproved ? (
              <div className="flex items-center gap-2 px-4 py-2 rounded-xl bg-green-950/30 border border-green-800/30">
                <CheckCircle size={16} className="text-[#10B981]" />
                <span className="text-sm font-semibold text-[#10B981]">Plan Approved</span>
              </div>
            ) : (
              <Button onClick={handleApprove} disabled={approving} className="gap-2 whitespace-nowrap">
                {approving ? (approvingMessage || 'Preparing…') : 'Approve plan — start learning'}
                <ArrowRight size={16} />
              </Button>
            )
          )}
        </div>

        {/* Stats */}
        {tab === 'ai-plan' && totalVisible > 0 && (
          <div className="mt-6 grid grid-cols-3 gap-4">
            {[
              { label: 'Sessions', value: totalVisible, color: '#7C3AED' },
              { label: 'Total time', value: `~${Math.floor(totalMins / 60)}h ${totalMins % 60}m`, color: '#06B6D4' },
              { label: arcGroups.size > 1 ? 'Arcs' : 'Arc', value: arcGroups.size, color: '#A855F7' },
            ].map((stat) => (
              <Card key={stat.label} className="p-4 text-center">
                <p className="text-2xl font-bold" style={{ color: stat.color }}>{stat.value}</p>
                <p className="text-xs text-[#475569] mt-0.5">{stat.label}</p>
              </Card>
            ))}
          </div>
        )}

        {/* Progress bar (active state only) */}
        {isPlanApproved && tab === 'ai-plan' && totalVisible > 0 && (
          <div className="mt-4">
            <div className="flex items-center justify-between mb-1">
              <span className="text-xs text-[#475569]">{completedCount} of {totalVisible} complete</span>
              <span className="text-xs text-[#475569]">{Math.round((completedCount / totalVisible) * 100)}%</span>
            </div>
            <div className="h-1 rounded-full bg-[#1E1E1E] overflow-hidden">
              <motion.div
                className="h-full bg-[#7C3AED] rounded-full"
                initial={{ width: 0 }}
                animate={{ width: `${(completedCount / totalVisible) * 100}%` }}
                transition={{ duration: 0.6 }}
              />
            </div>
          </div>
        )}
      </motion.div>

      {/* Tab switcher */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.1 }}
        className="flex gap-1 p-1 rounded-xl bg-[#111111] border border-[#1E1E1E] w-fit"
      >
        {tabs.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-colors ${
              tab === t.id ? 'bg-[#7C3AED] text-white' : 'text-[#475569] hover:text-[#94A3B8]'
            }`}
          >
            {t.icon}
            {t.label}
          </button>
        ))}
      </motion.div>

      {/* ─── AI Plan tab ─────────────────────────────────────────────────── */}
      {tab === 'ai-plan' && (
        <motion.div
          key="ai-plan"
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className="space-y-4"
        >
          {/* Arc groups */}
          {Array.from(arcGroups.entries()).map(([arcName, { sessions, arcType }]) => (
            <ArcSection
              key={arcName}
              arcName={arcName}
              arcType={arcType}
              sessions={sessions}
              completedIds={completedIds}
              currentSessionId={firstIncomplete?.session_id}
              onStartSession={(id) => {
                // id is db_session_id (UUID) when plan is approved, session_id slug otherwise
                const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(id)
                router.push(isUuid ? `/dashboard/sessions/${id}` : `/dashboard/sessions`)
              }}
              defaultExpanded
            />
          ))}

          {/* Free/Trial gate */}
          {isFreeOrTrial && (
            <div className="rounded-xl border border-[#333333] bg-[#111111] p-5">
              <div className="flex items-center gap-3">
                <Lock size={18} className="text-[#475569]" />
                <div className="flex-1">
                  <p className="text-sm font-semibold text-white">Unlock your full learning path</p>
                  <p className="text-xs text-[#475569] mt-0.5">10 sessions + AI recommendations + shadow queue</p>
                </div>
                <Button size="sm" onClick={() => router.push('/pricing')} className="whitespace-nowrap">
                  Upgrade to Starter →
                </Button>
              </div>
            </div>
          )}

          {/* Recommendations section */}
          {!isFreeOrTrial && recommendations.length > 0 && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.3 }}
              className="space-y-3 pt-2"
            >
              <div className="border-t border-[#1E1E1E] pt-4">
                <p className="text-sm font-semibold text-white mb-0.5">Recommended for you</p>
                <p className="text-xs text-[#475569] mb-3">Topics we think you&apos;ll benefit from next</p>
                <AnimatePresence>
                  {recommendations.slice(0, recLimit).map((rec) => (
                    <RecommendationCard
                      key={rec.session_id}
                      recommendation={rec}
                      onAccept={handleAcceptRecommendation}
                      onDismiss={handleDismissRecommendation}
                    />
                  ))}
                </AnimatePresence>
              </div>
            </motion.div>
          )}

          {/* Bottom CTAs */}
          {!isPlanApproved && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4 }}
              className="flex gap-4 items-center pt-2"
            >
              <Button onClick={handleApprove} disabled={approving} size="lg" className="gap-2">
                {approving ? (approvingMessage || 'Preparing…') : 'Approve & start learning'}
                <ArrowRight size={18} />
              </Button>
              <button
                className="text-sm text-[#475569] hover:text-[#94A3B8] transition-colors"
                onClick={() => router.push('/topics')}
              >
                Change topics →
              </button>
            </motion.div>
          )}

          {isPlanApproved && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4 }}
              className="flex items-center gap-4 flex-wrap pt-2"
            >
              <Button onClick={() => router.push('/dashboard/sessions')} size="lg" className="gap-2">
                Go to Sessions
                <ArrowRight size={18} />
              </Button>
              <button
                className="text-sm text-[#475569] hover:text-[#94A3B8] transition-colors"
                onClick={() => router.push('/topics')}
              >
                Change topics →
              </button>
            </motion.div>
          )}
        </motion.div>
      )}

      {/* ─── Browse tab ──────────────────────────────────────────────────── */}
      {tab === 'browse' && (
        <motion.div
          key="browse"
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className="space-y-6"
        >
          {customPlan && (
            <div className="rounded-xl border border-[#7C3AED]/30 bg-[#7C3AED]/5 p-5 space-y-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <LayoutList size={16} className="text-[#A855F7]" />
                  <h3 className="text-base font-bold text-white">
                    {customPlan.sessions.length} sessions · {customPlan.totalMinutes} min total
                  </h3>
                </div>
                <Button size="sm" onClick={handleApprove} disabled={approving} className="gap-1">
                  {approving ? (approvingMessage || 'Preparing…') : 'Approve this plan'} <ArrowRight size={13} />
                </Button>
              </div>
            </div>
          )}

          <div>
            <div className="flex items-center gap-2 mb-4">
              <BookOpen size={16} className="text-[#06B6D4]" />
              <h2 className="text-lg font-bold text-white">Catalog</h2>
              <span className="text-xs text-[#475569] ml-1">Expand domains → check what you want to learn</span>
            </div>
            <TopicTree onBuild={handleBuildFromSelection} building={building} />
          </div>
        </motion.div>
      )}
    </div>
  )
}
