import { NextRequest, NextResponse } from 'next/server'
import { requireSessionAuth } from '@/lib/session-auth'

import { createSupabaseAdminClient } from '@/lib/supabase'
import { ROLES } from '@/lib/learning/taxonomy'
import type { CuratedTopic } from '@/lib/curriculum/catalog-curator'

// Cache is considered fresh for 45 days
const CACHE_MAX_AGE_MS = 45 * 24 * 60 * 60 * 1000

interface TopicRow {
  id: string
  title: string
  description: string
  domain_id: string
  relevant_roles: string[]
  relevant_maturity: string[]
  tags: string[]
}

interface RoleTopicCacheRow {
  topics: CuratedTopic[]
  generated_at: string
}

/**
 * GET /api/topics/catalog
 *
 * Returns curated topics for the authenticated user's role×industry×maturity.
 * Cache-first: reads from role_topic_cache (pre-generated by Claude education specialist).
 * Falls back to the live topic_catalog query if the cache is empty or stale (>45 days).
 *
 * Response shape (cache hit):
 *   { featured: CuratedTopic[], other: TopicRow[], role, industry, maturity, from_cache: true, cached_at, seeded }
 *
 * Response shape (cache miss / fallback):
 *   { featured: CuratedTopic[], other: TopicRow[], role, industry, maturity, from_cache: false, seeded }
 */
export async function GET(request: NextRequest) {
  const { userId, error } = await requireSessionAuth(request)
  if (error) return error

  // Query params are a fallback for brand-new users whose DB profile isn't saved yet
  const url = new URL(request.url)
  const paramRole = url.searchParams.get('role') ?? null
  const paramDomains = url.searchParams.get('domains')?.split(',').filter(Boolean) ?? []

  const supabase = createSupabaseAdminClient()

  // Fetch user profile fields needed for filtering
  const { data: user } = await supabase
    .from('users')
    .select('role, domains, primary_domain, domain_proficiency, industry, ai_maturity')
    .eq('id', userId!)
    .single()

  const userRole = user?.role ?? paramRole ?? null
  const userIndustry: string = (user?.industry as string | null) ?? 'general'
  const userMaturity: string = (user?.ai_maturity as string | null) ?? 'beginner'

  const userDomains: string[] = Array.isArray(user?.domains) && user.domains.length > 0
    ? user.domains
    : paramDomains
  const primaryDomain = user?.primary_domain ?? userDomains[0] ?? null

  // If we have nothing to filter on, expand the role-based fallback
  // by pulling primary domains from the role definition
  let expandedDomains = userDomains
  if (expandedDomains.length === 0 && userRole) {
    const roleDef = ROLES.find((r) => r.id === userRole)
    if (roleDef) {
      expandedDomains = roleDef.primaryDomains.slice(0, 6)
    }
  }

  // ─── CACHE LOOKUP ──────────────────────────────────────────────────────────
  if (userRole && userIndustry && userMaturity) {
    const { data: cacheRow } = await supabase
      .from('role_topic_cache')
      .select('topics, generated_at')
      .eq('role', userRole)
      .eq('industry', userIndustry)
      .eq('maturity', userMaturity)
      .single()

    if (cacheRow) {
      const row = cacheRow as RoleTopicCacheRow
      const generatedAt = new Date(row.generated_at)
      const isFresh = Date.now() - generatedAt.getTime() < CACHE_MAX_AGE_MS
      const topics = Array.isArray(row.topics) ? row.topics : []

      if (isFresh && topics.length > 0) {
        console.log(`[topics/catalog] Cache hit for ${userRole}×${userIndustry}×${userMaturity} (${topics.length} topics)`)
        return NextResponse.json({
          featured: topics as CuratedTopic[],
          other: [] as TopicRow[],
          role: userRole,
          industry: userIndustry,
          maturity: userMaturity,
          from_cache: true,
          cached_at: row.generated_at,
          seeded: true,
        })
      }
    }
  }

  // ─── FALLBACK: LIVE TOPIC_CATALOG QUERY ───────────────────────────────────
  console.log(`[topics/catalog] Cache miss for ${userRole}×${userIndustry}×${userMaturity} — running live query`)

  const [roleResult, domainResult] = await Promise.all([
    userRole
      ? supabase
          .from('topic_catalog')
          .select('id, title, description, domain_id, relevant_roles, relevant_maturity, tags')
          .contains('relevant_roles', [userRole])
          .eq('is_custom', false)
          .limit(120)
      : { data: [] as TopicRow[], error: null },

    expandedDomains.length > 0
      ? supabase
          .from('topic_catalog')
          .select('id, title, description, domain_id, relevant_roles, relevant_maturity, tags')
          .in('domain_id', expandedDomains)
          .eq('is_custom', false)
          .limit(120)
      : { data: [] as TopicRow[], error: null },
  ])

  const seen = new Set<string>()
  const merged: TopicRow[] = []

  // Domain results first (more targeted to user's explicit selections)
  for (const row of ((domainResult.data ?? []) as TopicRow[])) {
    if (!seen.has(row.id)) {
      seen.add(row.id)
      merged.push(row)
    }
  }
  // Then role-based results (broader relevance)
  for (const row of ((roleResult.data ?? []) as TopicRow[])) {
    if (!seen.has(row.id)) {
      seen.add(row.id)
      merged.push(row)
    }
  }

  // Sort: primary domain first, then rest of user's domains, then by domain_id alphabetically
  merged.sort((a, b) => {
    const aPrimary = a.domain_id === primaryDomain ? 0 : 1
    const bPrimary = b.domain_id === primaryDomain ? 0 : 1
    if (aPrimary !== bPrimary) return aPrimary - bPrimary

    const aUserDomain = expandedDomains.indexOf(a.domain_id)
    const bUserDomain = expandedDomains.indexOf(b.domain_id)
    const aIdx = aUserDomain === -1 ? 999 : aUserDomain
    const bIdx = bUserDomain === -1 ? 999 : bUserDomain
    if (aIdx !== bIdx) return aIdx - bIdx

    return a.domain_id.localeCompare(b.domain_id)
  })

  // If catalog is empty (not yet seeded), return empty so topics page falls back
  if (merged.length === 0) {
    console.log(`[topics/catalog] No catalog topics found for user=${userId} role=${userRole}`)
    return NextResponse.json({
      featured: [] as CuratedTopic[],
      other: [] as TopicRow[],
      role: userRole,
      industry: userIndustry,
      maturity: userMaturity,
      from_cache: false,
      seeded: false,
    })
  }

  // Get the role's primary domains for the featured/other split
  const roleDef = userRole ? ROLES.find((r) => r.id === userRole) : null
  const primaryDomains = roleDef ? roleDef.primaryDomains : expandedDomains

  // Split merged into featured (first 18 topics in role's primaryDomains) and other (rest)
  // This gives the frontend the same shape regardless of cache vs fallback
  const featuredRows: TopicRow[] = []
  const otherRows: TopicRow[] = []

  for (const row of merged) {
    if (featuredRows.length < 18 && primaryDomains.includes(row.domain_id)) {
      featuredRows.push(row)
    } else {
      otherRows.push(row)
    }
  }

  // Map TopicRow to CuratedTopic shape for consistent frontend interface
  const featuredAsCurated: CuratedTopic[] = featuredRows.map((row, idx) => ({
    title: row.title,
    description: row.description,
    domain_id: row.domain_id,
    is_trending: false,
    trending_score: 0,
    popularity_rank: idx + 1,
    tags: row.tags,
  }))

  return NextResponse.json({
    featured: featuredAsCurated,
    other: otherRows,
    role: userRole,
    industry: userIndustry,
    maturity: userMaturity,
    from_cache: false,
    seeded: true,
  })
}
