/**
 * Builds Clio's three session documents — injected as the ElevenLabs system prompt.
 *
 * Document 1 — session_brief:  agenda, personalisation, skips, rules (no Claude needed)
 * Document 2 — topic_context:  rich Q&A knowledge base (generated by topic-context-generator)
 * Document 3 — session_script: TEACH/CHECKPOINT/PROBE/CONTINUE per section (no Claude needed)
 *
 * All three are stored in walkthrough_state and combined into the agent.prompt.prompt
 * override when starting the ElevenLabs WebSocket session.
 */

// ─── MINIMAL INLINE TYPES ─────────────────────────────────────────────────────

interface CheckpointVariants {
  v1_perfect?: string
  v2_correct_incomplete?: string
  v3_partial_gap?: string
  v4_adjacent_wrong?: string
  v5_incorrect?: string
  v6_dont_know?: string
  v7_explain_again?: string
}

interface TrainingSegment {
  type: 'TEACH' | 'CHECKPOINT' | 'ICE_BREAKER' | 'PROBE' | 'CONTINUE' | 'CLOSE'
  content: string
  variants?: CheckpointVariants
}

interface TrainingScript {
  subtopic_title: string
  subtopic_slug: string
  segments: TrainingSegment[]
}

interface SectionMeta {
  subtopicTitle: string
  sessionTitle?: string
}

// CONTENT-02: minimal shape of the `script` field session-bookends.ts
// populates on SessionOverview/SessionSummary sections' `data`. Optional and
// additive — every other section type's `data` shape is untouched.
interface BookendScript {
  teach: string
  checkpoint: string
  continue: string
}

interface Section {
  id: string
  type?: string
  meta: SectionMeta
  // Structurally permissive on purpose: callers pass TemplateSection[] (a
  // discriminated union whose `data` shape varies per section type). Only
  // SessionOverview/SessionSummary sections are expected to carry `script`
  // here; every other section type's `data` is read only via the `unknown`
  // cast in getBookendScript() below, never assumed to have this shape.
  data?: unknown
}

// CONTENT-02: safely read `data.script` off a section without widening the
// exported `Section` type's `data` field beyond `unknown` — avoids type
// conflicts with the many concrete `data` shapes TemplateSection's
// discriminated union already defines in lib/templates/types.ts.
function getBookendScript(section: Section): BookendScript | null {
  const data = section.data as { script?: BookendScript } | undefined
  return data?.script ?? null
}

interface BuildDocsInput {
  sessionTitle: string
  sessionIndex?: number | null
  topicId: string
  sections: Section[]
  trainingScripts: (TrainingScript | null)[]
  topicContextDocs: (string | null)[]   // one per section, from topic-context-generator
  skippedTopics?: string[]
  userRole?: string
  userIndustry?: string
  learnerProfile?: string | null        // Document 4 — from buildProfileContextForClio()
  sessionDurationMins?: number          // effective duration after minutes-balance cap
  isOnDemandSingleSection?: boolean     // ONDEMAND-02: true only for live-conductor on-demand sessions
                                         // (Overview-only at session start; remaining tabs generated live
                                         // on advance_tab). Explicit boolean, set by the caller — never
                                         // inferred from sections.length or title matching inside this
                                         // function. Defaults to false/undefined for every existing caller.
}

// ─── DOCUMENT 1: SESSION BRIEF ────────────────────────────────────────────────

export function buildSessionBrief(input: Omit<BuildDocsInput, 'topicContextDocs' | 'trainingScripts'>): string {
  const {
    sessionTitle, sessionIndex, sections, skippedTopics = [],
    userRole, userIndustry, sessionDurationMins,
    isOnDemandSingleSection = false,
  } = input
  const sessionLabel = sessionIndex != null ? `Session ${sessionIndex}` : 'Session'

  const agendaLines = sections.map((s, i) => {
    const skipped = skippedTopics.includes(s.meta.subtopicTitle)
    return `  ${i + 1}. ${s.meta.subtopicTitle}${skipped ? '  [SKIP — say "We\'re skipping this one today" and move on immediately]' : ''}`
  })

  const timePerSection = sessionDurationMins && sections.length > 0
    ? Math.round(sessionDurationMins / sections.length)
    : null

  return [
    `=== SESSION BRIEF ===`,
    ``,
    `${sessionLabel}: ${sessionTitle}`,
    userRole ? `Executive: ${userRole}${userIndustry ? ` in ${userIndustry}` : ''}` : '',
    `Sections: ${sections.length}`,
    sessionDurationMins != null
      ? `Available time: ${sessionDurationMins} minutes total${timePerSection ? ` (~${timePerSection} min per section)` : ''}. Deliver every concept clearly — prioritise understanding over speed.`
      : '',
    ``,
    `TODAY'S AGENDA — follow this order exactly, no deviations:`,
    ...agendaLines,
    ``,
    `OPENING SEQUENCE — do this first, before anything else:`,
    `Call show_visual({ section_index: 0 }) immediately when the session starts.`,
    `This shows the Session Overview. While it loads, say: "Let me pull up today's overview."`,
    isOnDemandSingleSection
      ? `Briefly walk through the agenda (read the section titles aloud), then begin teaching this tab's content directly — there is only one section prepared at the start; each additional topic is generated live, one at a time, only when you call advance_tab.`
      : `Briefly walk through the agenda (read the section titles aloud), then proceed to Section 1.`,
    `Do NOT begin any TEACH content until after the overview has been shown and the agenda read.`,
    `After the final bridge and 2-sentence summary, call show_visual({ section_index: ${sections.length + 1} }) to show the closing Summary screen, THEN call end_session.`,
    ``,
    `=== BEHAVIOURAL RULES ===`,
    `1. NEVER ask what the participant wants to cover — the agenda is fixed.`,
    `2. NEVER ask about their role or background — it is already known.`,
    `3. Call show_visual at the start of every section before you begin speaking about it. Always pass section_index (Overview = 0; section 1 = 1, section 2 = 2, etc.).`,
    `4. After delivering TEACH, always ask the verification question — do not skip it.`,
    `5. IMPORTANT — SCRIPT FORMAT: Labels in [STAGE DIRECTION — DO NOT SAY] brackets are stage directions only — never speak them aloud. Only speak the text that follows the label.`,
    `6. Use the reframe fallback only when the participant expresses confusion or asks you to explain differently.`,
    `7. Use the bridge to next section before calling show_visual for the next section.`,
    `8. For quick off-script questions: answer briefly from the TOPIC KNOWLEDGE BASE, then return to script.`,
    `9. For complex or off-topic questions: do NOT try to answer in depth. Say something close to "Great question — let's save that for next time so I can give it a proper answer," then return to the script. Do not call any tool for this.`,
    `10. After delivering the final bridge for the FINAL section (section ${sections.length}/${sections.length}): summarise what was covered in exactly 2 sentences, then immediately call end_session. Do NOT ask a follow-up question. Do NOT wait for the participant to respond first.`,
    `11. Teach with patience, not pace. After delivering TEACH, pause briefly before asking the verification question — give the participant a moment to absorb. If you sense uncertainty, slow down. The goal is understanding, not coverage speed.`,
  ].filter((l) => l !== '').join('\n')
}

// ─── DOCUMENT 2: TOPIC CONTEXT ────────────────────────────────────────────────

export function buildTopicContext(
  sections: Section[],
  topicContextDocs: (string | null)[]
): string {
  const blocks = sections.map((s, i) => {
    const doc = topicContextDocs[i]
    if (doc) return doc
    // Fallback if context doc not generated yet
    return [
      `## ${s.meta.subtopicTitle}`,
      `(Full context not yet generated — coach from the session script and key concepts only.)`,
    ].join('\n')
  })

  return [
    `=== TOPIC KNOWLEDGE BASE ===`,
    `Reference this when answering questions. Do NOT read it out verbatim.`,
    `Use it to give accurate, confident answers that go beyond the prepared script.`,
    ``,
    ...blocks,
  ].join('\n\n')
}

// ─── SHARED: rotating checkpoint fallback (item 21) ───────────────────────────

/**
 * Default verification-question phrasing used only when a section has no
 * LLM-generated CHECKPOINT segment (fallback path). Previously a single fixed
 * string repeated verbatim every section it fired for — rotates through a
 * small set of natural variants keyed by section index so a session that hits
 * this fallback more than once doesn't repeat the same line word-for-word.
 */
const CHECKPOINT_FALLBACK_VARIANTS = [
  'How does that land for you?',
  'Does that make sense so far?',
  'What questions does that raise for you?',
  'How are you thinking about that?',
]

function checkpointFallback(sectionIndex: number): string {
  return CHECKPOINT_FALLBACK_VARIANTS[sectionIndex % CHECKPOINT_FALLBACK_VARIANTS.length]
}

// ─── DOCUMENT 3: SESSION SCRIPT ───────────────────────────────────────────────

export function buildSessionScript(
  sections: Section[],
  trainingScripts: (TrainingScript | null)[]
): string {
  const totalSections = sections.length

  const scriptBlocks = sections.map((section, i) => {
    const title = section.meta.subtopicTitle

    // CONTENT-02: SessionOverview/SessionSummary carry their own real, pure-
    // template spoken content on section.data.script (built by
    // buildOverviewTeachContent/buildSummaryTeachContent in
    // lib/templates/session-bookends.ts) instead of a TrainingScript entry —
    // read from there, not from trainingScripts[i], for these two types only.
    // No other section type's handling changes below this branch.
    const isBookend = section.type === 'SessionOverview' || section.type === 'SessionSummary'
    const bookendScript = isBookend ? getBookendScript(section) : null

    const script = trainingScripts[i] ?? null

    const get = (type: TrainingSegment['type']) =>
      script?.segments.find((s) => s.type === type)?.content ?? null

    const teach = bookendScript ? bookendScript.teach : get('TEACH')
    const checkpointSegment = script?.segments.find((s) => s.type === 'CHECKPOINT') ?? null
    const checkpoint = bookendScript ? bookendScript.checkpoint : (checkpointSegment?.content ?? null)
    const checkpointVariants = bookendScript ? null : (checkpointSegment?.variants ?? null)
    const probe = bookendScript ? null : get('PROBE')
    const cont = bookendScript ? bookendScript.continue : get('CONTINUE')

    const variantBlock = checkpointVariants
      ? [
          ``,
          `[STAGE DIRECTION — DO NOT SAY] After they answer, pick the response that fits:`,
          `V1 (nailed it + added insight)  → ${checkpointVariants.v1_perfect ?? '(Celebrate their point + deepen it, then move to the bridge)'}`,
          `V2 (right but incomplete)       → ${checkpointVariants.v2_correct_incomplete ?? '(Acknowledge correct part + supply the missing piece)'}`,
          `V3 (partially right, gap)       → ${checkpointVariants.v3_partial_gap ?? '(Validate + fill the gap + re-anchor to the key takeaway)'}`,
          `V4 (adjacent, wrong direction)  → ${checkpointVariants.v4_adjacent_wrong ?? '(Redirect without saying wrong + reframe simply)'}`,
          `V5 (incorrect)                  → ${checkpointVariants.v5_incorrect ?? '(Affirm their thinking + correct clearly + re-explain with analogy)'}`,
          `V6 (I don't know)              → ${checkpointVariants.v6_dont_know ?? '(Normalise uncertainty + strip back to simplest explanation)'}`,
          `V7 (explain again)             → ${checkpointVariants.v7_explain_again ?? '(Completely different angle, simpler language, avoid repeating same words)'}`,
          `After any variant: deliver the bridge and proceed. If after V6/V7 still uncertain: deliver the bridge anyway — don't loop.`,
        ]
      : []

    const lines = [
      `--- SECTION ${i + 1}/${totalSections}: "${title}" --- [call show_visual({ section_index: ${i + 1} })]`,
      ``,
      `[STAGE DIRECTION — DO NOT SAY] Deliver teaching content after show_visual({ section_index: ${i + 1} }):`,
      teach ?? `(No script — explain the key concepts from the knowledge base in plain language.)`,
      ``,
      `[STAGE DIRECTION — DO NOT SAY] Verification question — ask after TEACH:`,
      checkpoint ?? checkpointFallback(i),
      ...variantBlock,
      ``,
      `[STAGE DIRECTION — DO NOT SAY] Reframe fallback — use if participant seems uncertain:`,
      probe ?? `Let me try a different angle.`,
      ``,
      i < totalSections - 1
        ? `[STAGE DIRECTION — DO NOT SAY] Bridge to next section:`
        : `[STAGE DIRECTION — DO NOT SAY] Final bridge — say this after verification response, then summarise 2 sentences, then call end_session immediately:`,
      cont ?? (i < totalSections - 1 ? `Good. Let's move to the next section.` : `That wraps up today's session.`),
    ]

    return lines.join('\n')
  })

  return [
    `=== SESSION SCRIPT ===`,
    `Deliver each section's TEACH script after calling show_visual.`,
    `Speak naturally — these are your words, not a teleprompter.`,
    ``,
    `SCREEN CONTROL:`,
    `- Call show_visual FIRST, then speak. Visual and voice must always be in sync.`,
    `- Always pass section_index (0-based integer) — each section header above shows the exact value to use.`,
    `- While the visual loads (1–2 sec), say: "Let me pull that up — [one-sentence teaser]. There we go."`,
    `- If screen loads instantly: skip the bridge and go straight to TEACH.`,
    ``,
    ...scriptBlocks,
  ].join('\n')
}

// ─── SINGLE-SECTION SCRIPT FORMATTER (used by split-mode injection) ───────────

/**
 * Formats one section's training script in the same structure buildSessionScript produces
 * for that section, but standalone — used by split mode to inject a single tab's script
 * via sendContextualUpdate at tab-advance time.
 *
 * @param section     The TemplateSection-like object with meta.subtopicTitle
 * @param script      The TrainingScript for this section (may be null)
 * @param sectionNum  1-based section number (e.g. section_index value)
 * @param totalSections  Total number of content sections (excluding overview)
 */
export function formatSingleSectionScript(
  section: Section,
  script: TrainingScript | null,
  sectionNum: number,
  totalSections: number
): string {
  const title = section.meta.subtopicTitle

  const get = (type: TrainingSegment['type']) =>
    script?.segments.find((s) => s.type === type)?.content ?? null

  const teach = get('TEACH')
  const checkpointSegment = script?.segments.find((s) => s.type === 'CHECKPOINT') ?? null
  const checkpoint = checkpointSegment?.content ?? null
  const checkpointVariants = checkpointSegment?.variants ?? null
  const probe = get('PROBE')
  const cont = get('CONTINUE')

  const variantBlock = checkpointVariants
    ? [
        ``,
        `[STAGE DIRECTION — DO NOT SAY] After they answer, pick the response that fits:`,
        `V1 (nailed it + added insight)  → ${checkpointVariants.v1_perfect ?? '(Celebrate their point + deepen it, then move to the bridge)'}`,
        `V2 (right but incomplete)       → ${checkpointVariants.v2_correct_incomplete ?? '(Acknowledge correct part + supply the missing piece)'}`,
        `V3 (partially right, gap)       → ${checkpointVariants.v3_partial_gap ?? '(Validate + fill the gap + re-anchor to the key takeaway)'}`,
        `V4 (adjacent, wrong direction)  → ${checkpointVariants.v4_adjacent_wrong ?? '(Redirect without saying wrong + reframe simply)'}`,
        `V5 (incorrect)                  → ${checkpointVariants.v5_incorrect ?? '(Affirm their thinking + correct clearly + re-explain with analogy)'}`,
        `V6 (I don't know)              → ${checkpointVariants.v6_dont_know ?? '(Normalise uncertainty + strip back to simplest explanation)'}`,
        `V7 (explain again)             → ${checkpointVariants.v7_explain_again ?? '(Completely different angle, simpler language, avoid repeating same words)'}`,
        `After any variant: deliver the bridge and proceed. If after V6/V7 still uncertain: deliver the bridge anyway — don't loop.`,
      ]
    : []

  const isLast = sectionNum >= totalSections

  const lines = [
    `[SPLIT MODE — SECTION ${sectionNum} SCRIPT INJECTED]`,
    `--- SECTION ${sectionNum}/${totalSections}: "${title}" --- [call show_visual({ section_index: ${sectionNum} })]`,
    ``,
    `[STAGE DIRECTION — DO NOT SAY] Deliver teaching content after show_visual({ section_index: ${sectionNum} }):`,
    teach ?? `(No script — explain the key concepts from the knowledge base in plain language.)`,
    ``,
    `[STAGE DIRECTION — DO NOT SAY] Verification question — ask after TEACH:`,
    checkpoint ?? checkpointFallback(sectionNum),
    ...variantBlock,
    ``,
    `[STAGE DIRECTION — DO NOT SAY] Reframe fallback — use if participant seems uncertain:`,
    probe ?? `Let me try a different angle.`,
    ``,
    isLast
      ? `[STAGE DIRECTION — DO NOT SAY] Final bridge — say this after verification response, then summarise 2 sentences, then call end_session immediately:`
      : `[STAGE DIRECTION — DO NOT SAY] Bridge to next section:`,
    cont ?? (isLast ? `That wraps up today's session.` : `Good. Let's move to the next section.`),
  ]

  return lines.join('\n')
}

// ─── COMBINED BUILD (convenience entry point) ─────────────────────────────────

export interface ClioSessionDocs {
  session_brief: string
  topic_context: string
  session_script: string
  /** Combined system prompt for ElevenLabs agent.prompt.prompt override */
  system_prompt: string
}

/**
 * @param mode  'all-upfront' (default): session_script included in system_prompt.
 *              'split': session_script computed and stored but omitted from system_prompt;
 *              scripts are injected per-tab at tab-advance time via injectContext.
 */
export function buildAllClioDocs(
  input: BuildDocsInput,
  mode: 'all-upfront' | 'split' = 'all-upfront'
): ClioSessionDocs {
  const session_brief = buildSessionBrief({
    sessionTitle: input.sessionTitle,
    sessionIndex: input.sessionIndex,
    topicId: input.topicId,
    sections: input.sections,
    skippedTopics: input.skippedTopics,
    userRole: input.userRole,
    userIndustry: input.userIndustry,
    isOnDemandSingleSection: input.isOnDemandSingleSection,
  })

  const topic_context = buildTopicContext(input.sections, input.topicContextDocs)
  const session_script = buildSessionScript(input.sections, input.trainingScripts)

  // In split mode: omit session_script from system_prompt — it is injected per-tab
  // via adapter.injectContext() at tab-advance time in WalkthroughClient.
  const parts = mode === 'split'
    ? [session_brief, topic_context]
    : [session_brief, topic_context, session_script]
  if (input.learnerProfile) parts.push(input.learnerProfile)

  const system_prompt = parts.join('\n\n---\n\n')

  return { session_brief, topic_context, session_script, system_prompt }
}
