/**
 * Builds Clio's three session documents — injected as the ElevenLabs system prompt.
 *
 * Document 1 — session_brief:  agenda, personalisation, skips, rules (no Claude needed)
 * Document 2 — topic_context:  rich Q&A knowledge base (generated by topic-context-generator)
 * Document 3 — session_script: TEACH/CHECKPOINT/PROBE/CONTINUE per section (no Claude needed)
 *
 * All three are stored in walkthrough_state and combined into the agent.prompt.prompt
 * override when starting the ElevenLabs WebSocket session.
 */

// ─── MINIMAL INLINE TYPES ─────────────────────────────────────────────────────

interface TrainingSegment {
  type: 'TEACH' | 'CHECKPOINT' | 'PROBE' | 'CONTINUE'
  content: string
}

interface TrainingScript {
  subtopic_title: string
  subtopic_slug: string
  segments: TrainingSegment[]
}

interface SectionMeta {
  subtopicTitle: string
  sessionTitle?: string
}

interface Section {
  id: string
  meta: SectionMeta
}

interface BuildDocsInput {
  sessionTitle: string
  sessionIndex?: number | null
  topicId: string
  sections: Section[]
  trainingScripts: (TrainingScript | null)[]
  topicContextDocs: (string | null)[]   // one per section, from topic-context-generator
  skippedTopics?: string[]
  userRole?: string
  userIndustry?: string
}

// ─── DOCUMENT 1: SESSION BRIEF ────────────────────────────────────────────────

export function buildSessionBrief(input: Omit<BuildDocsInput, 'topicContextDocs' | 'trainingScripts'>): string {
  const { sessionTitle, sessionIndex, sections, skippedTopics = [], userRole, userIndustry } = input
  const sessionLabel = sessionIndex != null ? `Session ${sessionIndex}` : 'Session'

  const agendaLines = sections.map((s, i) => {
    const skipped = skippedTopics.includes(s.meta.subtopicTitle)
    return `  ${i + 1}. ${s.meta.subtopicTitle}${skipped ? '  [SKIP — say "We\'re skipping this one today" and move on immediately]' : ''}`
  })

  return [
    `=== SESSION BRIEF ===`,
    ``,
    `${sessionLabel}: ${sessionTitle}`,
    userRole ? `Executive: ${userRole}${userIndustry ? ` in ${userIndustry}` : ''}` : '',
    `Sections: ${sections.length}`,
    ``,
    `TODAY'S AGENDA — follow this order exactly, no deviations:`,
    ...agendaLines,
    ``,
    `=== BEHAVIOURAL RULES ===`,
    `1. NEVER ask what the participant wants to cover — the agenda is fixed.`,
    `2. NEVER ask about their role or background — it is already known.`,
    `3. Call show_visual at the start of every section before you begin speaking about it.`,
    `4. After delivering TEACH, always ask the CHECKPOINT question — do not skip it.`,
    `5. Use PROBE only when the participant expresses confusion or asks you to explain differently.`,
    `6. Use CONTINUE to bridge before calling show_visual for the next section.`,
    `7. For quick off-script questions: answer briefly from the TOPIC KNOWLEDGE BASE, then return to script.`,
    `8. For complex or off-topic questions: call defer_question. Say "Great question — I've saved it for next time."`,
    `9. When the session ends: summarise what was covered in 2 sentences, then call end_session.`,
    `10. Keep pace — this is executive time. Do not dwell on any section beyond the script + one follow-up.`,
  ].filter((l) => l !== '').join('\n')
}

// ─── DOCUMENT 2: TOPIC CONTEXT ────────────────────────────────────────────────

export function buildTopicContext(
  sections: Section[],
  topicContextDocs: (string | null)[]
): string {
  const blocks = sections.map((s, i) => {
    const doc = topicContextDocs[i]
    if (doc) return doc
    // Fallback if context doc not generated yet
    return [
      `## ${s.meta.subtopicTitle}`,
      `(Full context not yet generated — coach from the session script and key concepts only.)`,
    ].join('\n')
  })

  return [
    `=== TOPIC KNOWLEDGE BASE ===`,
    `Reference this when answering questions. Do NOT read it out verbatim.`,
    `Use it to give accurate, confident answers that go beyond the prepared script.`,
    ``,
    ...blocks,
  ].join('\n\n')
}

// ─── DOCUMENT 3: SESSION SCRIPT ───────────────────────────────────────────────

export function buildSessionScript(
  sections: Section[],
  trainingScripts: (TrainingScript | null)[]
): string {
  const totalSections = sections.length

  const scriptBlocks = sections.map((section, i) => {
    const script = trainingScripts[i] ?? null
    const title = section.meta.subtopicTitle

    const get = (type: TrainingSegment['type']) =>
      script?.segments.find((s) => s.type === type)?.content ?? null

    const teach = get('TEACH')
    const checkpoint = get('CHECKPOINT')
    const probe = get('PROBE')
    const cont = get('CONTINUE')

    const lines = [
      `--- SECTION ${i + 1}/${totalSections}: "${title}" ---`,
      ``,
      `TEACH — say this after calling show_visual for this section:`,
      teach ?? `(No script — explain the key concepts from the knowledge base in plain language.)`,
      ``,
      `CHECKPOINT — ask this after TEACH to verify understanding:`,
      checkpoint ?? `How does that land for you?`,
      ``,
      `PROBE — use this if they seem uncertain or ask you to explain differently:`,
      probe ?? `Let me try a different angle.`,
      ``,
      `CONTINUE — say this to bridge before calling show_visual for the next section:`,
      cont ?? (i < totalSections - 1 ? `Good. Let's move to the next section.` : `That wraps up today's session.`),
    ]

    return lines.join('\n')
  })

  return [
    `=== SESSION SCRIPT ===`,
    `Deliver each section's TEACH script after calling show_visual.`,
    `Speak naturally — these are your words, not a teleprompter.`,
    ``,
    `SCREEN CONTROL:`,
    `- Call show_visual FIRST, then speak. Visual and voice must always be in sync.`,
    `- While the visual loads (1–2 sec), say: "Let me pull that up — [one-sentence teaser]. There we go."`,
    `- If screen loads instantly: skip the bridge and go straight to TEACH.`,
    ``,
    ...scriptBlocks,
  ].join('\n')
}

// ─── COMBINED BUILD (convenience entry point) ─────────────────────────────────

export interface ClioSessionDocs {
  session_brief: string
  topic_context: string
  session_script: string
  /** Combined system prompt for ElevenLabs agent.prompt.prompt override */
  system_prompt: string
}

export function buildAllClioDocs(input: BuildDocsInput): ClioSessionDocs {
  const session_brief = buildSessionBrief({
    sessionTitle: input.sessionTitle,
    sessionIndex: input.sessionIndex,
    topicId: input.topicId,
    sections: input.sections,
    skippedTopics: input.skippedTopics,
    userRole: input.userRole,
    userIndustry: input.userIndustry,
  })

  const topic_context = buildTopicContext(input.sections, input.topicContextDocs)
  const session_script = buildSessionScript(input.sections, input.trainingScripts)

  const system_prompt = [session_brief, topic_context, session_script].join('\n\n---\n\n')

  return { session_brief, topic_context, session_script, system_prompt }
}
